### ISSUE TITLE
Estructura y diseño de la página de la tabla de clasificación

### ISSUE THREAD

**Issue by pramos-m** [NullSquad/peer-2-pong#102]
### **Crear la estructura de la pagina de la tabla de clasificación**
---
#### **Criterios de aceptación**  

Participante clave: @ruiznaomy13 

- [ ] La página debe tener una estructura que permita ubicar cada componente en su lugar.  
   - [ ] Tabla de clasificaciones
   - [ ] Podio
   - [ ] flecha para volver a la pagina de atras
   - [ ] boton de Join y para darse de baja
- [ ] La disposición de los elementos debe seguir un diseño claro e intuitivo.
- [ ] La página debe ser responsiva para que se visualice correctamente en diferentes dispositivos.  
- [ ] El diseño de la pagina (fondo) debe seguir la guía de estilos del proyecto (colores, tipografía, etc.).

**Comment by ZenitsuTHB** [comment]
This aint DONE yet, acceptance criteria to review
